import { Injectable } from '@nestjs/common';
import * as client from 'prom-client';

@Injectable()
export class MetricsService {
  private register: client.Registry;
  private apiCallsCounter: client.Counter;
  private successCounter: client.Counter;
  private errorCounter: client.Counter;
  private randomValueGauge: client.Gauge;
  private requestDurationHistogram: client.Histogram;

  constructor() {
    this.register = new client.Registry();

    // 기본 메트릭 수집 (CPU, 메모리 등)
    client.collectDefaultMetrics({ register: this.register });

    // 커스텀 메트릭: API 호출 카운터
    this.apiCallsCounter = new client.Counter({
      name: 'api_calls_total',
      help: 'Total number of API calls',
      labelNames: ['endpoint'],
      registers: [this.register],
    });

    // 커스텀 메트릭: 성공 카운터
    this.successCounter = new client.Counter({
      name: 'api_success_total',
      help: 'Total number of successful API calls',
      registers: [this.register],
    });

    // 커스텀 메트릭: 에러 카운터
    this.errorCounter = new client.Counter({
      name: 'api_errors_total',
      help: 'Total number of API errors',
      registers: [this.register],
    });

    // 커스텀 메트릭: 랜덤 값 게이지
    this.randomValueGauge = new client.Gauge({
      name: 'random_value',
      help: 'Random value generated by the API',
      registers: [this.register],
    });

    // 커스텀 메트릭: 요청 지속 시간 히스토그램
    this.requestDurationHistogram = new client.Histogram({
      name: 'http_request_duration_seconds',
      help: 'Duration of HTTP requests in seconds',
      labelNames: ['method', 'route', 'status_code'],
      registers: [this.register],
    });
  }

  incrementApiCalls(endpoint: string): void {
    this.apiCallsCounter.inc({ endpoint });
  }

  incrementSuccessCounter(): void {
    this.successCounter.inc();
  }

  incrementErrorCounter(): void {
    this.errorCounter.inc();
  }

  setRandomValue(value: number): void {
    this.randomValueGauge.set(value);
  }

  async getMetrics(): Promise<string> {
    return this.register.metrics();
  }
}

